//! Feedback screen: analyses/trends and suggestions generated by the agent.
//! Read-only in Phase 2; periodic generation enters Phase 6.

use ratatui::{
    layout::Rect,
    style::{Color, Modifier, Style},
    text::{Line, Span},
    widgets::{Block, Borders, Paragraph, Wrap},
    Frame,
};

use super::App;

pub fn render(f: &mut Frame, area: Rect, app: &App) {
    let mut lines: Vec<Line> = Vec::new();
    if app.feedback.is_empty() {
        lines.push(Line::styled(
            "No feedback yet. The agent will generate periodic analyses and suggestions (Phase 6).",
            Style::default().fg(Color::DarkGray),
        ));
    } else {
        for fb in &app.feedback {
            lines.push(Line::from(Span::styled(
                fb.created_at.clone(),
                Style::default().fg(Color::DarkGray),
            )));
            lines.push(Line::from(Span::styled(
                fb.summary.clone(),
                Style::default()
                    .fg(Color::Cyan)
                    .add_modifier(Modifier::BOLD),
            )));
            for sug in fb.suggestions.lines() {
                if !sug.trim().is_empty() {
                    lines.push(Line::from(sug.to_string()));
                }
            }
            lines.push(Line::from(""));
        }
    }

    let p = Paragraph::new(lines)
        .wrap(Wrap { trim: false })
        .block(Block::default().borders(Borders::ALL).title(" Feedback "));
    f.render_widget(p, area);
}
